### ISSUE TITLE
Jetpack instantly stops downwards momentum

### ISSUE THREAD

**Issue by edcolmar** [Pantong51/AdvancedMovementComponent#3]
**Describe the bug**
When falling, and tapping the jetpack, the movement is redirected instantly upwards.

**To Reproduce**
1. fall vertically
2. tap jetpack
3. see movement switch instantly to upwards motion.

**Expected behavior**
Tapping the jetpack while falling should reduce downwards motion proportional to jetpack force.

**Additional context**
Have I missed a configuration setting to enable this behavior?

**Comment by Pantong51** [comment]
Hmmm, it's been a while since I've used this plugin. I think if you are not using a curve it will just apply a flat change in velocity. But that might not actually be true. I'll take a look although I've mostly abandoned this project. My current goal is to recreate the movement system in the network prediction plugin framework to give more flexibility and reduce movement speed hacks. But i agree the expected behavior should be that it reduces downwards motion = to jetpack force

**Comment by edcolmar** [comment]
Thanks.  I know you're not working on this one anymore.  We're actively using it, and I was hoping there would be an easy fix, or setting I had missed.

**Comment by Pantong51** [comment]
I think I internally used jump to start the jetpack, that uses launch character. If you override DoJump in the base movement component and switch if falling to not override the character's velocity that should work.

**Comment by edcolmar** [comment]
Thanks for the hint.  I got it working.  Would you like a PR for this?

**Comment by Pantong51** [comment]
Sure that sounds good
